import React, { useState, useEffect} from 'react'
import { Link } from 'react-router-dom'
import EmployeeService from '../services/EmployeeService'

// code for the list all employee functionality

const ListEmployeeComponent = () => {

    const [employees, setEmployees] = useState([])
    // usestate is react hook that returns tuple of state and function that lets us update the state
    // generated by usestate snippet annotation which imports usestate from react
    // const[state,function]=usestate()

    //useeffect is used to perform API requests 
    useEffect(() => {
        getAllEmployees();
    }, [])
    const getAllEmployees=()=>{
    EmployeeService.getAllEmployees().then((response)=>{
        setEmployees(response.data)
        console.log(response.data);
    }).catch(error => {
        console.log(error);
  })
}

    const deleteEmployee=(employeeId) =>{
        EmployeeService.deleteEmployee(employeeId).then((response) =>{
            getAllEmployees();
        }).catch(error => {
            console.log(error);
        })
    }
    

  return (
    <div className="container">
        <h2 className="text-center">List Employees</h2>
        {/* now adding link to add employees */}
        <Link to="/add-employee" className="btn btn-primary mb-2"> Employee Registration </Link>
        <table className="table table-bordered table striped">
            <thead>
                <th>Employee ID</th> 
                <th>Employee FirstName</th>
                <th>Employee LastName</th>
                <th>Employee Email</th>
                <th>Actions</th>
            </thead>
            <tbody>
                {
                employees.map(
                    employee =>
                    <tr>
                        <td>{employee.id}</td>
                        <td>{employee.firstName}</td>
                        <td>{employee.lastName}</td>
                        <td>{employee.email}</td>
                        <td>
                            {/* <Link className="btn btn-info" to={'/update-employee/${employee.id}'}>Update</Link> */}
                            <button className='btn btn-danger' onClick={() => deleteEmployee(employee.id)} 
                            style={{marginLeft:"10px"}}>Delete
                            </button>
                        </td>
                        </tr>
                )
                }
            </tbody>
        </table>
    </div>
  )

            }
export default ListEmployeeComponent